### ISSUE TITLE
Add support of RESTful services (EPIC)

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#862]
- [x] https://github.com/scalecube/scalecube-services/issues/863
- [x] https://github.com/scalecube/scalecube-services/issues/856
- [x] https://github.com/scalecube/scalecube-services/issues/857
- [x] https://github.com/scalecube/scalecube-services/issues/861

**Comment by artem-v** [comment]
Closing, fixed in https://github.com/scalecube/scalecube-services/pull/872.
